sudo: false

language: node_js

node_js:
  - node

before_script:
  - npm install
  - npm run pretty

script:
  - npm run test:coveralls

notifications:
  email: false
  webhooks: https://outlook.office.com/webhook/ab920c11-0284-4fe6-b3c2-d7ad0e24c850@450e6824-88ab-4ad2-914d-b0f385da600c/TravisCI/6de2ff36774b4eeda79eb88062b1baf0/dcd9d052-1f29-470d-bfc8-e8a3ef7cab72
