#
# @version 0.5.0
# @author [Grayson Orr](https://github.com/grayson-orr)
#

sudo: false

language: node_js

node_js:
  - node

before_script:
  - npm install
  - npm run pretty

script:
  - npm run test:coveralls

notifications:
  email: false

