version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/npm_and_yarn/helpers"
    update_schedule: "live"

  - package_manager: "python"
    directory: "/python/helpers"
    update_schedule: "live"