version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/package.json"
    update_schedule: "live"
    target_branch: "master"
    default_labels:
      - "dependencies"
      - "dependabot"
    allowed_updates:
      - match:
          update_type: "all"